services:
  db:
    image: postgres:latest
    container_name: krost-dev-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: krost
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: